services:
  here-be-dragons-bot:
    image: here-be-dragons-bot
    container_name: HereBeDragonsBot
    pull_policy: never
    build: .
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 32m
    volumes:
      - /srv/HereBeDragonsBot/data:/app/data:Z
